### ISSUE TITLE
Container and more

### ISSUE THREAD

**Issue by alienatedsec** [NosIreland/solsimon2#1]
Hi @NosIreland 

I want to say thank you for the solismon3, as it works perfectly with my WiFi stick. It allows me to produce some good graphs:

![image](https://user-images.githubusercontent.com/73167064/209239586-d4d62182-3a69-4ae2-944a-c3aeb0220d70.png)

However, now I am looking into swapping my WiFi stick for the LAN version. There are certain benefits of using LAN over WiFi for my use case. Hence, I need solismon2 to work with it.

Two questions:
1. Can you build a container version?
2. Before actioning the above, could you upgrade the code to include all recently developed (if any additional) solismon3 capabilities into solismon2?

Please let me know if you are willing to act on the above; otherwise, I will need to spend more on bringing it to the level I wish was good for my use case.

**Comment by NosIreland** [comment]
I don't think I fully understad why you want to use solismon2.
Solismon2 using ModBus protocol to pull data directly from Solis without using WiFi or LAN stick. As you just changing WiFi stick to LAN you can just keep using Solismon3

**Comment by alienatedsec** [comment]
@NosIreland The LAN stick is Modbus TCP and does not need to wrap the packet as the WiFi stick via Modbus RTU; hence, the LAN stick needs Solismon2 rather than Solismon3 to work unless you tell me there is no difference between 2 and 3. (?)

You can find more from this comment https://github.com/jmccrohan/pysolarmanv5/issues/5#issuecomment-1240638954

**Comment by NosIreland** [comment]
Interesting, I thought that Lan stick would work the same way as WiFi stick.
Since I do not have LAN stick I have no way in testing the code. I was using Solismon2 with Volison Modbus gateway that I no longer have.
You can try changing values below. Set IP of Lan stick and port to 8899 as per link you provided and see if you can get anything. The registers in the code should work.
```
MODBUS_SERVER = "XXX.XXX.XXX.XXX"
MODBUS_PORT = 502
MODBUS_TIMEOUT = 7
```

**Comment by alienatedsec** [comment]
I am waiting for the LAN stick to arrive but preparing for the 'migration'. I am sure solismon2 will work. I need it to work from the container and authenticate with MQTT.

**Comment by jmccrohan** [comment]
@alienatedsec Where did you buy your DLS-L from? I'm interested to switching from the DLS-W to DLS-L for native Modbus TCP support.

**Comment by alienatedsec** [comment]
Hi @jmccrohan 

I got it from TradeSparky.com  

But...

It worked initially with SolaX Modbus integration but ended up being a faulty stick. I didn't have a chance to test it with the SolisMon2 as of yet. 

I reloaded it with plenty of firmware versions, and Solis decided to replace it via the RMA process.

**Comment by jmccrohan** [comment]
@alienatedsec Thanks. Can you share the first five digits of the DLS-L
serial number please?

I have one here 19051xxxxxx that doesn't support Morbus TCP. Device is
listening on port 30003 but no reply.

**Comment by alienatedsec** [comment]
> @alienatedsec Thanks. Can you share the first five digits of the DLS-L
> serial number please?
> 
> I have one here 19051xxxxxx that doesn't support Morbus TCP. Device is
> listening on port 30003 but no reply.
> 
@jmccrohan 
What's the firmware version? Also, you can change the work mode if you have one in your settings.

**Comment by jmccrohan** [comment]
@alienatedsec Firmware is ME-121001-V1.0.6(202011261020). Work mode is set to Modbus TCP.

![image](https://user-images.githubusercontent.com/315209/210595983-24944e77-bc93-44af-b594-aab4211effea.png)

What are the first five digits of the S/N? I think there are a few different hardware revisions of the DLS-L.

**Comment by alienatedsec** [comment]
@jmccrohan Please send me an email `alienatedsec@gmail.com`
